---
title: "Oct26"
author: "Ixtaccihuatl Obregon"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
```

Start with code you've written outside for your function 

```{r}
x_vec = rnorm(25, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

Writing a function!

```{r}
z_scores = function(x) {
  if(!is.numeric(x)){
    stop("Argument x should be numeric")
  }else if (length(x) == 1){
    stop("Z score cannot be computed for length 1 vectors")
  }
  z = (x - mean(x)) / sd(x)
  z
}

z_scores(x_vec)
```

```{r, eval=FALSE}
z_scores(x = 3)

z_scores("my name is ixta")

z_scores(iris)

z_scores(sample(c(TRUE, FALSE), 25, replace = TRUE))

```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  list(mean = mean_x, 
       sd = sd_x)
}

mean_and_sd(x_vec)
```

## Start getting means and stds

```{r}
x_vec = rnorm(n = 30, mean = 5, sd = 0.5)

tibble(
  mean = mean(x_vec), 
  sd = sd(x_vec)
)
```

Write a function that uses 'n', a true mean, and true SD as inputs. 

```{r}
sim_mean_sd = function(n_obs, mu, sigma){
  x_vec = rnorm(n = n_obs, mean = mu, sd = sigma)

  tibble(
  mean = mean(x_vec), 
  sd = sd(x_vec)
)
}

sim_mean_sd(n_obs = 30, mu = 5, sigma = 0.5)
```













